pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "SMS listener"
include ':app'
//include ':sms_plus_calls_handling'
include ':test'
//
//include ':common'
//include ':libraries:commonfiles'
